### PR TITLE
Adding Key Press Delay Logic and Fix a Bug and Spelling

### PR DESCRIPTION
**Pull request by gligorov**
Added logic to allow delay to control when key press is raised as event to prevent double event raising for key press. Default is set to 500 ms.
Fixed spelling on the Released Event
Fixed Bug on check for Release event.

## Checklist:

- [ ] I've placed my contribution in the appropriate section.
- [ ] I've choosen a good name for it and I've checked the repo for duplicates.
- [ ] I've added a readme.md following the provided template (TBD). 
- [ ] My code follows the code style of this project.
- [ ] I've tidy my files inside the contribution folder.
- [ ] I've edited the repo README.md to include the mention and link to my contribution. It's under the proper section and the link is correct.
- [ ] The code builds.

Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>

### CODE REVIEW

**Review by josesimoes — COMMENTED** [review]
Nice catch on the spelling!😁

On the debounce, thta was supposed to be handled with the debounce property... Have you tried that? It's more efficient as it's handled right on the native code.

**Comment by gligorov** [comment]
Yes, attempted to do this using the Debounce, but the results are not the same; Increasing value to 500ms works for a button press or two, then no further response. Retested the test program one more time again, same results.  Using the key press delay timeout, seems to allow the app to run fine, and the user interaction is much more normal on the key press.

**Comment by josesimoes** [comment]
You are correct on the above about debouncing! The current implementation wont' work. actually it will fail detection of the INT pin the increased too much. I'll remove the property.

**Review by josesimoes — APPROVED** [review]
LGTM

**Pull request merged**
