### PR TITLE
Add drive for DS18B20

### PR DESCRIPTION
**Pull request by up-streamer**
Add DS18B20 drive.
Tested using ESP32.
Program.cs contains test sample.

## Checklist:

- [x] I've placed my contribution in the appropriate section.
- [x] I've choosen a good name for it and I've checked the repo for duplicates.
- [x] I've added a readme.md following the provided template (TBD). 
- [x] My code follows the code style of this project.
- [x] I've tidy my files inside the contribution folder.
- [ ] I've edited the repo README.md to include the mention and link to my contribution. It's under the proper section and the link is correct.
- [x] The code builds.

### CODE REVIEW

**Review by josesimoes — CHANGES_REQUESTED** [review]
Nice work here! Thanks for sharing. 👏 

Could you please update the repo readme to include a link to this?

**Comment by up-streamer** [comment]
One thing. I left the packages on the pull request. I think now, it is not necessary as the packages will certainly be updated in near future. :)

Did you mean a link of the usage of this like a post in Hackster.io or in my blog?

**Comment by josesimoes** [comment]
The packages haven't been included on the PR, so we're good with that.

On the README entry: you're supposed to add a link to this new folder on the README of this repo [here](https://github.com/nanoframework/nf-Community-Contributions/blob/master/README.md#drivers)

**Comment by up-streamer** [comment]
Oh I see...  Done.

**Review by josesimoes — APPROVED** [review]
LGTM!

That's exactly it

**Pull request merged**
