### PR TITLE
BME280 Driver

### PR DESCRIPTION
**Pull request by vgolovanov**
## Checklist:

- [x] I've placed my contribution in the appropriate section.
- [x] I've choosen a good name for it and I've checked the repo for duplicates.
- [x] I've added a readme.md following the provided template (TBD). 
- [x] My code follows the code style of this project.
- [x] I've tidy my files inside the contribution folder.
- [x] I've edited the repo README.md to include the mention and link to my contribution. It's under the proper section and the link is correct.
- [x] The code builds.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nanoframework/nf-Community-Contributions?pullRequest=33) <br/>All CLA requirements met.

**Review by josesimoes — CHANGES_REQUESTED** [review]
Thanks for adding this.
Could you please add a link to this at the appropriate section in the main readme?

After that, please go through the check list to validate that you have covered all of those and check them. 😉

**Comment by vgolovanov** [comment]
Link  to Readme.md file added.

**Review by josesimoes — APPROVED** [review]
Remove the readme from the library. The rest look OK. Thanks!

**Pull request merged**
