### PR TITLE
 added nanoFramework.CoAP library

### PR DESCRIPTION
**Pull request by vgolovanov**
## Checklist:

- [ ] I've placed my contribution in the appropriate section.
- [ ] I've choosen a good name for it and I've checked the repo for duplicates.
- [ ] I've added a readme.md following the provided template (TBD). 
- [ ] My code follows the code style of this project.
- [ ] I've tidy my files inside the contribution folder.
- [ ] I've edited the repo README.md to include the mention and link to my contribution. It's under the proper section and the link is correct.
- [ ] The code builds.

### CODE REVIEW

**Comment by Ellerbach** [comment]
Thank you for your contribution, the core idea is to move such devices to https://github.com/nanoframework/nanoFramework.IoT.Device for consistency.
Would be great if you can contribute to the new repository rather than this one. We will keep for this one only reference to other repositories and moved the code from the drivers/bindings/devices (call them as you like) to the new repository.
And the BME280 and all the BM family is already fully supported and already fully implemented.

**Comment by vgolovanov** [comment]
BME280 driver commited a long time ago. I don't know why older commits merged into the new one. Right now i commited a port of the CoAP library. Is that correct, that  nanoFramework.IoT.Device is the right place for the network protocol library ?

> Thank you for your contribution, the core idea is to move such devices to https://github.com/nanoframework/nanoFramework.IoT.Device for consistency.
> Would be great if you can contribute to the new repository rather than this one. We will keep for this one only reference to other repositories and moved the code from the drivers/bindings/devices (call them as you like) to the new repository.
> And the BME280 and all the BM family is already fully supported and already fully implemented.

**Comment by Ellerbach** [comment]
> BME280 driver commited a long time ago. I don't know why older commits merged into the new one. Right now i commited a port of the CoAP library. Is that correct, that  nanoFramework.IoT.Device is the right place for the network protocol library ?

Yes, correct, IoT.Device is the right destination for new code like for BME.
Now, if it's "just" a link, then then, this repository is the correct place.

So, you should close this PR, just take the CoAP README and reopen a clean PR.

**Review by josesimoes — CHANGES_REQUESTED** [review]
Can you please rebase so only the relevant files for CoAP show up?

**Pull request closed without merging**
