### PR TITLE
Add MFRC522 RFID card driver

### PR DESCRIPTION
**Pull request by up-streamer**
## Checklist:

- [x] I've placed my contribution in the appropriate section.
- [x] I've chosen a good name for it and I've checked the repo for duplicates.
- [x] I've added a readme.md following the provided template (TBD). 
- [x] My code follows the code style of this project.
- [x] I've tidy my files inside the contribution folder.
- [x] I've edited the repo README.md to include the mention and link to my contribution. It's under the proper section and the link is correct.
- [x] The code builds.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nanoframework/nf-Community-Contributions?pullRequest=36) <br/>All CLA requirements met.

**Review by josesimoes — APPROVED** [review]

**Comment by josesimoes** [comment]
@up-streamer seems that there is a conflict with the main README... Can you please take a look at that? Thanks.

**Comment by up-streamer** [comment]
New contributions arrived since time I forked this repository. Solved.

**Review by josesimoes — APPROVED** [review]
Thanks!

**Pull request merged**
