### PR TITLE
 BLE SPP  library to transfer > 256 byte arrays

### PR DESCRIPTION
**Pull request by hbraasch**
## Checklist:

- [x] I've placed my contribution in the appropriate section.
- [x] I've choosen a good name for it and I've checked the repo for duplicates.
- [x] I've added a readme.md following the provided template (TBD). 
- [ ] My code follows the code style of this project.
- [x] I've tidy my files inside the contribution folder.
- [x] I've edited the repo README.md to include the mention and link to my contribution. It's under the proper section and the link is correct.
- [x] The code builds.

### CODE REVIEW

**Comment by hbraasch** [comment]
Improvement made based on feedback. Due to large changes by adding complete project files, a new PR was created.

**Comment by Ellerbach** [comment]
I see we don't have a proper .gitignore at the root! I should add it! Otherwise, all the libs, dll, etc are showing up :-) And thanks a lot for adjusting all this already! Looks really good all up.
Let me know if you need any help in all this

**Comment by Ellerbach** [comment]
So once, you'll pull the changes from your own branch, you'll get a new .gitignore which will prevent to check all the non needed files.
That will bring a lot of clarity to the PR and only the code and the proper readme will remain! Next push with more adjustments in your code and it will be clean to have a second look.
Thanks again for all the efforts!

**Comment by hbraasch** [comment]
Thanks for the instructions. I’m definitely NOT a GitHub power user. Regards Sent from Mail for Windows From: Laurent EllerbachSent: Tuesday, March 22, 2022 9:26 PMTo: nanoframework/nf-Community-ContributionsCc: Heinrich Braasch; MentionSubject: Re: [nanoframework/nf-Community-Contributions] BLE SPP library to transfer > 256 byte arrays (PR #44) So once, you'll pull the changes from your own branch, you'll get a new .gitignore which will prevent to check all the non needed files.That will bring a lot of clarity to the PR and only the code and the proper readme will remain! Next push with more adjustments in your code and it will be clean to have a second look.Thanks again for all the efforts!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by josesimoes** [comment]
@hbraasch we should take care of this PR!
That branch of yours needs to be cleaned up. Does your repo allow write access from upstream maintainers?
If yes, me or @Ellerbach  can do that so the PR gets cleaned up. 😉

**Pull request closed without merging**
